name: Django CI (SQLite)

on:
  push:
    branches: ["main"]    
  pull_request:
    branches: 
       - main
       - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: feastflow.settings
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ghis Try to Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test --verbosity=2
